<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MonkeyIslandSpecialEditionSpriteEditor.PatchCli</RootNamespace>
    <AssemblyName>mi1se-walkbox-patch</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonkeyIslandSpecialEditionSpriteEditor.csproj" />
  </ItemGroup>

</Project>
